# Change these first
owner: ametis70 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

secrets:
  - UPTIME_DOMAIN
  - UPTIME_HTTPS
  - TELEGRAM_BOT_TOKEN
  - TELEGRAM_CHAT_ID

sites:
  - name: Homelab (TCP Ping)
    url: $UPTIME_DOMAIN
    check: "tcp-ping"

  - name: Homelab (Globalping)
    url: $UPTIME_DOMAIN
    type: globalping
    location: Argentina

  - name: Homelab (HTTPS)
    url: $UPTIME_HTTPS

notifications:
  - type: telegram
    bot-token: $TELEGRAM_BOT_TOKEN
    chat-id: $TELEGRAM_CHAT_ID

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
